### PR TITLE
Change class name to Version000009Date20190625000800

### PR DESCRIPTION
**Pull request by anaqreon**

### CODE REVIEW

**Comment by anaqreon** [comment]
This is related to the discussion in https://github.com/nextcloud/maps/pull/60

**Comment by eneiluj** [comment]
Well I'm almost sure if you install the app from scratch or if you just update the app this error won't show up.

I mean there is no mistake in naming it like it is in `rework-eneiluj`, your error is probably going to show up again if you do the exact same actions again.

Don't you think?

**Comment by anaqreon** [comment]
Coincidentally I just followed the same procedure a few minutes ago on a completely separate host machine because I wanted to try the map on a real server to test the device tracking, and the app was unable to install (using the current branch). I can't look at the log file at the moment to ensure the error was identical but the use of Docker should make this behavior fairly consistent, right?

**Comment by anaqreon** [comment]
I checked and it was the same error with the same solution to enable the app to install.

**Comment by eneiluj** [comment]
Yep my bad, I didn't really read your changes. Thanks for the PR!

**Pull request merged**
