### PR TITLE
Use non-deprecated call to add navigation entry

### PR DESCRIPTION
**Pull request by MorrisJobke**

### CODE REVIEW

**Comment by MorrisJobke** [comment]
cc @v1r0x  @e-alfred

**Comment by v1r0x** [comment]
Thanks for your patch @MorrisJobke 
Master is currently a deprecated branch. A rewrite is done in the `rework` branch. Sorry, going to update the README to make this clear.

**Comment by MorrisJobke** [comment]
Feel free to cherry pick or drop this completely - just wanted to give a heads up for you :)

**Comment by v1r0x** [comment]
Yeah, thanks :)
Try to remember it as soon as I have some time to work on it again ;)

**Comment by jancborchardt** [comment]
@eneiluj @v1r0x @MorrisJobke with the rework having been merged into master, is this still current or already fixed? :)

**Comment by jancborchardt** [comment]
And for reference, the only relevant commit seems to be this one: https://github.com/nextcloud/maps/pull/26/commits/7847fe2944aec564968d388bc3d8b5b9fc5a3524

**Comment by MorrisJobke** [comment]
> @eneiluj @v1r0x @MorrisJobke with the rework having been merged into master, is this still current or already fixed? :)

It is already fixed in current master 👍

**Pull request closed without merging**
