### PR TITLE
Allow import from Google Takeout JSON

### PR DESCRIPTION
**Pull request by simonspa**
This PR allows to import favorites from a JSON file generated by Google Maps Takeout (Saved Places) and is a first step towards solving #66.

I'd be happy to receive some feedback and advice, especially on how to treat error conditions.

### CODE REVIEW

**Comment by jancborchardt** [comment]
@smihael @HollowedEmpire @ph00lt0 @walley @Thovi98 since you were active on "**Import Google Takeout Saved places #66**", could you review this pull request and test if it works? Thanks a lot! :)

**Comment by Thovi98** [comment]
> 
> 
> @smihael @HollowedEmpire @ph00lt0 @walley @Thovi98 since you were active on "**Import Google Takeout Saved places #66**", could you review this pull request and test if it works? Thanks a lot! :)

Thank you for your great work ! I’d be glad to help you, but I don’t know how to proceed to do this (I’m on Nextcloud on Yunohost, so path files are different).
And in my way to put Google out of my life, I’ve deleted all my maps saved places and history, so I could not help you for this point anymore :( 

But thank you a lot for everything you do day by day to improve this - already incredible - app !
I will try to help you to test other PR when I have a better comprehension of this.

**Comment by ph00lt0** [comment]
I have installed the changes, but I am not able to select the json.

**Comment by simonspa** [comment]
Have you recompiled the JavaScript?

**Comment by ph00lt0** [comment]
Yeah I did execute the make command, however that did not help. I fully deleted the app and reinstalled it and then it worked.

**Comment by simonspa** [comment]
Hm, that's odd looking at the code I have no idea where counting could go wrong. Are you sure you only had 253 locations in your JSON? Would you mind sharing it (privately) with me?

**Comment by ph00lt0** [comment]
I also couldnt not find any evidence that this would be cause by your contribution. I am not willing share the file as this includes to much information.

**Comment by simonspa** [comment]
Sure, that's what I presumed - it's why we want to move it away from Google in the first place, no? :)

**Comment by ph00lt0** [comment]
Yep, well I did leave google behind some time ago. I still hoped for a import function in Nextcloud of my data export. So thanks a lot for your effort.

**Comment by jancborchardt** [comment]
@simonspa I hope to test this soon (although I have no Google Takeout content so I can only test the interface), any screenshots would help a lot to review the design quicker. :)

**Comment by simonspa** [comment]
Hi @jancborchardt 

here you go:

image

image

image


A JSON file with reference data as returned by Google Takeout can be found in the linked issue.

**Comment by ph00lt0** [comment]
The json data looks like this @jancborchardt 

`{
  "type" : "FeatureCollection",
  "features" : [
 {
    "geometry" : {
      "coordinates" : [ 4.895168, 52.370216 ],
      "type" : "Point"
    },
    "properties" : {
      "Google Maps URL" : "http://maps.google.com/?q=Amsterdam,+Nederland&ftid=0x47c63fb5949a7755:0x6600fd4cb7c0af8d",
      "Location" : {
        "Latitude" : "52.370216",
        "Longitude" : "4.895168"
      },
      "Published" : "2018-02-01T12:00:51Z",
      "Title" : "Amsterdam, Nederland",
      "Updated" : "2018-02-01T12:00:51Z"
    },
    "type" : "Feature"
  }
]
}
`

**Comment by jancborchardt** [comment]
Ah perfect! Only 1 thing: Could you adjust the title to clarify GeoJSON like: `GeoJSON (Google Maps)`, then it’s clear we can also import from Google Maps. :)

**Comment by tacruc** [comment]
Should Google takeout JSON be mentioned somewhere on the second picture?

**Comment by simonspa** [comment]
Updated:

image

**Comment by jancborchardt** [comment]
Btw @simonspa @ph00lt0 we have a Maps team channel on our Nextcloud Talk instance – I can add you there with guest accounts if you like? It makes communication much easier. :)

**Comment by ph00lt0** [comment]
@jancborchardt sure fine with me.

**Comment by simonspa** [comment]
@jancborchardt yes, please do so!

**Pull request merged**
