### PR TITLE
make the photos nav item collapsible

### PR DESCRIPTION
**Pull request by eastyu**

### CODE REVIEW

**Comment by tacruc** [comment]
Hi @eastyu,
thanks for your PR. But I think it needs some explanation.
The following questions should be addressed.

- Why?
Photos have no sub item so what should be shown or hidden with the collapsable function.
- Did you test it?
I don't expect this PR to have the desired consequences as the new frontend in the master branch uses the vue navigation component in src/components/.
Therefore I'm not sure whether the navigation template is used at all.

**Comment by eastyu** [comment]
Hi @tacruc ,

please see the screenshot, the text comes over the icon. after I add the class for this item. it shows normal.

image

**Comment by tacruc** [comment]
Hm interesting and this is also happening on the master branch?

**Comment by eastyu** [comment]
I just upgrade to v0.1.10 and the issue is gone. it's fixed somehow. close this PR now.

**Pull request closed without merging**
