### PR TITLE
Fix "endswith" declaration and remove contact groups colors

### PR DESCRIPTION
**Pull request by eneiluj**
There was a huge problem with a little function declared multiple times. It was not detected wen running the tests or loading the main app page...

I also removed the colors for contact groups as it's probably useless. I've put the main theming color for all group icons instead. We could also set their color to black/grey.

As you wish.

### CODE REVIEW

**Comment by jancborchardt** [comment]
> I also removed the colors for contact groups as it's probably useless. I've put the main theming color for all group icons instead. We could also set their color to black/grey.

I’d indeed say let’s use simple black so it’s uniform. :) Otherwise good!

**Comment by eneiluj** [comment]
A'ight. I agree. It's now black.

**Comment by jancborchardt** [comment]
@anaqreon also check this out since it should fix the issue you reported at https://github.com/nextcloud/maps/issues/73 :)

**Comment by eneiluj** [comment]
@anaqreon I'll check that tomorrow. Thanks for the quality of your tests :smile:.

**Comment by eneiluj** [comment]
@anaqreon I did a quick fix to favorite export procedure. Could you export and try to import again?

Thanks again for finding this bug.

**Comment by eneiluj** [comment]
Btw, it's still far from perfect. Characters like "<" and ">" might be problematic. Export is very naive and should be converted to something using a proper library to write correct and clean XML.

**Comment by eneiluj** [comment]
Yep it really needs a clean implementation. I'll convert "<" and ">" for the moment but it will be much safer by writing with a library.

**Pull request merged**
