### PR TITLE
Hot fix #543 Images not loading

### LINKED ISSUE #543: images not opening in NC21
I just updated to NC21, but now I can no longer view images from maps, instead I see a spinner (the same files do view from Files and in the Photos app)

When looking at the console, I see that the preview is successfully fetched, but it is not shown. 

screenshot_2021-02-26-091745
[console-export-2021-2-26_9-15-49.txt](https://github.com/nextcloud/maps/files/6048350/console-export-2021-2-26_9-15-49.txt)

NC21.0.0, Maps 0.1.8

### PR DESCRIPTION
**Pull request by tacruc**
See #543 for disscussion

Signed-off-by: Arne Hamann <kontakt+github@arne.email>

### CODE REVIEW

**Comment by wronny** [comment]
working in my nc21 - many thanks!

**Review by wronny — APPROVED** [review]
working in my nc21 - many thanks!

**Comment by neuherzk** [comment]
working :)

**Comment by smalchow** [comment]
verified, it works

**Pull request merged**
