### PR TITLE
update composer and npm metadata files

### PR DESCRIPTION
**Pull request by eneiluj**
Those files are local and don't need to be tracked by the repo.

### CODE REVIEW

**Comment by tacruc** [comment]
https://github.com/nextcloud/maps/pull/292#issuecomment-584630014

**Comment by eneiluj** [comment]
Ok thanks for pointing to the comment.

Still it's a bit annoying since it seems only required to avoid the automatic npm "test" to fail. I would prefer to get rid of those and to make changes in the proper place to generate them before calling `npm ci`. What do you think?

**Comment by tacruc** [comment]
I have no preference, but maybe @gary-kim or @ChristophWurst pointing this out at the first time.

**Comment by gary-kim** [comment]
The point of dependency lock files are to ensure everyone has the exact same set of dependencies installed, no matter their environment. They are meant to be in the repo. They help make sure there are never any bugs that arise from having a different version of a dependency, speed up installing dependencies, and also help with security by storing the hash of all dependencies.

[package-lock.json documentation](https://docs.npmjs.com/files/package-lock.json) && [composer.lock documentation](https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control)

There's also some documentation about the reasons for lockfiles in npm [here](https://docs.npmjs.com/files/package-locks)

Whenever updates are required for dependencies for Javascript, npm, or in our case, dependabot, will automatically update the package-lock.json file as well. The same will happen for composer dependencies as well.

**Comment by eneiluj** [comment]
@gary-kim Ok thanks for the explanation. So we should not pay attention to the fact we will commit them often? We just commit them and that's it?

**Comment by gary-kim** [comment]
Normal changes should not be updating the lockfiles unless they involve changing dependencies. The fact that the app store template includes `composer update` as part of the setup process is strange. @ChristophWurst do you know why that's there?
https://github.com/nextcloud/maps/blob/c5e1f99cc5c5038d872abfb2dbb7e97b93d86a8f/Makefile#L79-L83

**Comment by eneiluj** [comment]
Thanks a lot for looking into it!

It might just be something to fix in the Makefile indeed.

**Comment by ChristophWurst** [comment]
> @ChristophWurst do you know why that's there?

Good catch. That doesn't seem right. Please fix the Makefile and also submit that for the template.

**Comment by eneiluj** [comment]
Thanks for #314.

So I reverted everything on this branch. Rebased on master and ran `make` which updated `package-lock.json`. All clear?

**Comment by gary-kim** [comment]
That's strange. What version of npm do you have installed? My system doesn't make that change.

**Comment by eneiluj** [comment]
Node version is v10.15.2 and npm is 5.8.0.

After upgrading npm to 6.13.7, `package-lock.json` is not changed anymore by running make.

Should we close this or is there anything left to do?

**Pull request closed without merging**
