### PR TITLE
Remove broken unique constraints

### PR DESCRIPTION
**Pull request by Tyil**
As per https://github.com/nextcloud/maps/issues/541, these constraints are broken. Maps are working fine (for me, at least) without these constraints.

### CODE REVIEW

**Comment by UweKrause** [comment]
@Tyil the DCO bot prevents you from merging, could you please make that bot happy?

**Comment by UweKrause** [comment]
and btw, after applying your fix, it looks like the installation has worked, but from now on, I get following error:
`Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_maps_tracks' doesn't exist`
Might be unrelated(?)

**Comment by Tyil** [comment]
On Sun, Mar 07, 2021 at 07:32:13PM +0000, Uwe Krause wrote:
> @Tyil the DCO bot prevents you from merging, could you please make that bot happy?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/nextcloud/maps/pull/542#issuecomment-792338211

I've amended my commit to include the Signed-off-by part.

-- 
With kind regards,

Patrick Spek


www:  https://www.tyil.nl/
mail: p.spek@tyil.nl
pgp:  1660 F6A2 DFA7 5347 322A  4DC0 7A6A C285 E2D9 8827

git:    https://git.tyil.nl/

**Review by odea — APPROVED** [review]

**Comment by tacruc** [comment]
I'm unshure If this modifications allown will fix the database migration on all setups.
This was  the fix I implemented on my development setup, but it was not sufficient allown. As after the fix Tables where missing.

So we have to make shure, that the fix works on:

- New Installations, which never enabled maps bevor
- Installations, which where running into the error, it might be that the migration is not reexecuted
- Installations, which where using maps, but not jet where running into the error.

**Comment by odea** [comment]
> and btw, after applying your fix, it looks like the installation has worked, but from now on, I get following error:
> `Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_maps_tracks' doesn't exist`
> Might be unrelated(?)

Same for me ! still unable to install maps...
Server version: Apache/2.4.41-4ubuntu3.1
PHP 7.4.3 (cli) (built: Oct 6 2020 15:47:56) ( NTS )
Nexcloud version: 21
Database: MariaDB 1:10.3.25-0ubuntu0.20.04.1
Where did you install Nextcloud from: Source

**Comment by tacruc** [comment]
Is it still an Issue with NC23 and after #568

**Comment by odea** [comment]
Hi, I can't say for NC23, I'm stuck with 22.2.5 (btw if someone can tell me if it's normal that would be great).
I don't remember what I did, but I managed to install 0.1.9 manually, it worked and updated well to 0.1.10.

**Comment by tacruc** [comment]
Redundand to #568

**Pull request closed without merging**
