### PR TITLE
Tacruc pel read exif data

### LINKED ISSUE #47: exif_read_data is making problems
On most of my jpegs php read exif is throwing errors. This is giving me a hard time to get 1000 picture in my test installation to do some performance testing. 

`exif_read_data(P1050526.JPG): Process tag(x013B=Artist ): Illegal components(0) at /srv/www/htdocs/server/lib/private/legacy/image.php#418`

I didn't manage to make it more stable, but the metadata app is reading them correctly. 
Some sample picture:
P1010498

### PR DESCRIPTION
**Pull request by tacruc**
fixes #47 is depending on #53

### CODE REVIEW

**Comment by eneiluj** [comment]
Nice:

You included all my changes in your PR. Please just push the related commit in ` tacruc-pel-read-exif-data` otherwise I will be reviewing my own commits like I said in the other PR :wink:.

**Comment by eneiluj** [comment]
To be more explicit: checkout master, create a branch from master, apply your changes and create the PR or force push to ` tacruc-pel-read-exif-data`.

**Comment by jancborchardt** [comment]
Is this branch still needed or should it be deleted @tacruc @eneiluj? :)

**Comment by eneiluj** [comment]
It was merge somewhere else. I would say: no, not needed.

**Pull request closed without merging**
