### PR TITLE
added "Download Track" button to AppNavigationTrackItem

### PR DESCRIPTION
**Pull request by wronny**
Hello, 
first of all congrats to many great improvements in maps. I like and use creating maps and sharing them. Due to the fact that I use it for sharing tracks I added a "Download Track" button, to being able to provide all in one share link.
Please review and merge if you like/agree on it. 
Thanks
Marcel

### CODE REVIEW

**Review by tacruc — COMMENTED** [review]
Hi @wronny,
Thanks for the feedback and your contribution.
I like the download in the app navigation.
What do we need a download link in the track right-click menu? Or I. The track metadata tab?

**Comment by wronny** [comment]
Hello @tacruc ,
Not sure if I got you correctly. Do you want me to add the track download button in the track right-click menu, too? I can add this as well if you want. Just let me know.

**Comment by tacruc** [comment]
First I wanted your opinion on it.
I think it might be useful, but maybe you thought already about it and had a reason against it.

**Comment by wronny** [comment]
Hello @tacruc,
I agreee. Adding it also to the track's right click menu makes sense. 
Added to this pull request, now. However looks like close-after-click does not work in this track context menu. Added auto close via click method, like also used for "Display elevation".

**Review by tacruc — APPROVED** [review]

**Review by tacruc — APPROVED** [review]

**Pull request merged**
