### PR TITLE
[WIP] Rework maps app

### PR DESCRIPTION
**Pull request by v1r0x**
This is a work in progress PR.

Since the current version relies on an old version of leaflet and a no longer supported tilelayer,  @jancborchardt and I decided to rework the whole app and update it to Leaflet 1.x.

This PR should cover the basic features of a maps app.

See https://github.com/nextcloud/maps/pull/15#issuecomment-324350873 for todo list

cc @nextcloud/maps

### CODE REVIEW

**Comment by jancborchardt** [comment]
Also cc @eneiluj of GpxPod and GpxEdit because we should work together on making this work directly in the one Maps app. :)

**Comment by jancborchardt** [comment]
For the record and to not have it only as one comment in a big issue, here’s the todo list taken from https://github.com/nextcloud/maps/issues/2#issuecomment-313360509 :)

the core scope is to provide an alternative to things like Google Maps, Apple Maps etc. This includes:

Basic core features:
- [ ] Map display
- [ ] Search
- [ ] Elements/POIs being clickable with further information shown
- [ ] Favorites (which can ideally be synced to mobile with Maps.me or OSMand)
- [ ] Routing (for walking, cycling, driving)

Advanced stuff:
- [ ] Ideally even public transport routing, but I know this is hard
- [ ] Integration with other apps like:
  - [ ] Contacts: showing them on the map, and also suggesting them in the search
  - [ ] Contacts: inside contacts with an address, show a little map widget for their location
  - [ ] Files/Gallery: Show photos in their location based on EXIF location data
  - [ ] Calendar: providing the Calendar app with a way to show a little map widget in an event when there is a location set. The other way around, show events which take place in the future and have a location set on that place in the map.
  - [ ] Mail: make location descriptions from mails clickable, or also show a small map widget like that
- [ ] In the future GPX track overlay, possibility to edit

**Comment by e-alfred** [comment]
Postgresql compatibility should be on the todo list too as mentioned here, if changes are necessary: https://github.com/nextcloud/maps/issues/19

**Comment by v1r0x** [comment]
> Routing (for walking, cycling, driving)

@jancborchardt I tried to add the [leaflet-routing-machine](https://github.com/perliedman/leaflet-routing-machine) to the app, but the builtin routing service (osrm) is "[down](https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server)". The mention Mapbox as alternative, but it requires an API key. Since there is no completely free routing service we should decide which one we want to use. IMO there are three options:
1. Mapbox (Supports at least car, bike and walking)
2. Mapzen (Supports at least car, bike, walking and transit; Geocoding, Autocomplete Search)
3. GraphHopper (Supports at least car, bike and walking)

I think mapzen has the most features and a good free plan. GraphHopper looks good as well. Not sure about the pricing plan of mapbox ("credit" based). Any thoughts?

**Comment by e-alfred** [comment]
@v1r0x Mapbox is also used by GNOME Maps since Mapquest shut down their free access. An API key shouldn't be a huge deal, the weather app also requires one to work (pulling data from Openweathermap).

Mapzen sounds surely better because it has more features that are useful for a map app after all. Transit data would be a good addition too.

One important issue I can see would be a good way to make transition to a new backend easier so the Mapquest debacle can be avoided if a provider closes down/cuts off free access.

**Comment by jancborchardt** [comment]
@v1r0x ok, let's go for Mapzen then. :)

Btw I think it would be good to merge this as early as possible so the PR doesn't become too big and people can also add improvements on top of the visible master. :)

**Comment by jancborchardt** [comment]
(As current master does not work at all anyway.)

**Comment by v1r0x** [comment]
> @v1r0x Mapbox is also used by GNOME Maps since Mapquest shut down their free access. An API key shouldn't be a huge deal, the weather app also requires one to work (pulling data from Openweathermap).

That's right. But should we add one (hardcoded) for all users or let them create one?

**Comment by jancborchardt** [comment]
Let's say we add a default one for everyone for now. As soon as there's issues we can talk about customization.

**Comment by v1r0x** [comment]
One question regarding the API key. Who should create the API Key? And are there any risks? E.g. abuse.

**Comment by e-alfred** [comment]
You could do it like in the Weather app that moved this setting into the admin section recently. I do not think that a normal user should be bothered with such a setting after all, only the admin should set it onece and everyone can use an app then.

**Comment by jancborchardt** [comment]
Yeah, API key should be an admin setting only. And would there be a default (or fair use) to ensure it works on simple install?

In any case, let's merge this branch as soon as possible @v1r0x, ok? :)

**Comment by v1r0x** [comment]
I'm unsure about a private API key as default. I also already have a private mapzen key, which I need for some private projects. What do you think about a "official" nextcloud key which is the default? Is this even possible? @jancborchardt

**Comment by jancborchardt** [comment]
How much could be used under that plan? Alternatively we could mail them about it and ask? cc @jospoortvliet

Also cc @freenerd who works at Mapbox, and @zeenix @mlundblad who work on GNOME Maps. How did you do it with the API key, and is there any way we could do it similarly with Nextcloud Maps?

Because we want to integrate Maps into Calendar, Contacts etc as well, so it makes sense to have a proper solution which works out of the box and doesn't need a technical person get an API key. :)

**Comment by v1r0x** [comment]
> How much could be used under that plan?

screenshot-2017-10-21 mapzen flex mapzen

**Comment by jancborchardt** [comment]
@v1r0x mind emailing both Mapzen and Mapbox to inquire if we can partner with them in some way?

@freenerd @zeenix @mlundblad any input how you handle it with GNOME Maps is appreciated :)

**Comment by v1r0x** [comment]
@jancborchardt No problem. I'll cc you in the mail and attach this issue. Ok?

**Comment by jancborchardt** [comment]
@v1r0x yep, great! :)

**Comment by e-alfred** [comment]
I built the app and noticed a few thing that could be improved:

- Search should show a drop down menu with matching items (if multiple results are found)
- If geolocation is used a popover should be displayed for the location identical to an item found using the search
- As you use leaflet now, selecting different types of maps (satellite, terrain, routes for example) would be great (like in GpxPod)

**Comment by e-alfred** [comment]
Game over for Mapzen, it will close down at the end of January:

https://mapzen.com/blog/migration/

I hope not a lot of work was done until now because it would be wasted once again. This also shows that the dependency on external services is extremely bad after all. Striving for self reliance or at least some kind of fallback sould be seriously considered, I think.

**Comment by v1r0x** [comment]
I tried to talk to mapzen devs, but didn't work out. So, not much work was done.
The leaflet-routing-machine is used (afair) in the old version and had a look at it for the rework, but afair it was very limited with plain osm. Thus, I decided to switch to something else. In general osm is very limited.
Maybe osrm is worth looking at it.

**Comment by e-alfred** [comment]
Seems like @eneiluj is now working on this app! @eneiluj Do you have some release we can test out? That would be awesome!

**Comment by eneiluj** [comment]
@e-alfred You can try rework-eneiluj branch. It's functional. I've written what's been done so far in #32. If we all agree, we (@tacruc and me) could work on rework branch and continue discussing in this PR thread instead of #32.

**Comment by jancborchardt** [comment]
@eneiluj awesome! Could you open a pull request based on that branch, then we can use that to discuss and collaborate. :)

**Comment by eneiluj** [comment]
@jancborchardt Should I make a PR to `master` or to `rework` ?

**Comment by jancborchardt** [comment]
@eneiluj since it’s based on rework but rework has been inactive, I think making the pull request to master is best. (cc @v1r0x just FYI)

**Comment by eneiluj** [comment]
@jancborchardt Here comes #44. Maps app is back on track :wink:.

**Pull request merged**
