### PR TITLE
attempt to fix bad inserted values for photo lat/lng

### LINKED ISSUE #95: [Doctrine\DBAL\Exception\DriverException]
maps:scan-photos fails on the file DSCN0009.JPG with:
```
In AbstractMySQLDriver.php line 106:                                                                                                                                                                                                               
                                                                                                                                                                                                                                                   
  [Doctrine\DBAL\Exception\DriverException]                                                                                                                                                                                                        
  An exception occurred while executing 'INSERT INTO `oc_maps_photos`(`file_id`,`lat`,`lng`,`user_id`,`date_taken`) VA                                                                                                                             
  LUES(?,?,?,?,?)' with params [144859, "\x4e\x41\x4e", "\x4e\x41\x4e", "arne", 1318384800]:                                                                                                                                                       
                                                                                                                                                                                                                                                   
  SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect double value: 'NAN' for column `owncloud`.`oc_maps_photos`.                                                                                                                             
  `lat` at row 1                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                   
Exception trace:                                                                                                                                                                                                                                   
 () at /srv/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:106                                                                                                                                              
 Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException() at /srv/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:169                                                                                                 
 Doctrine\DBAL\DBALException::wrapException() at /srv/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:145                                                                                                                 
 Doctrine\DBAL\DBALException::driverExceptionDuringQuery() at /srv/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:162                                                                                                        
 Doctrine\DBAL\Statement->execute() at /srv/www/nextcloud/lib/public/AppFramework/Db/Mapper.php:256                                                                                                                                                
 OCP\AppFramework\Db\Mapper->execute() at /srv/www/nextcloud/lib/public/AppFramework/Db/Mapper.php:130                                                                                                                                             
 OCP\AppFramework\Db\Mapper->insert() at /srv/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php:298                                                                                                                                        
 OCA\Maps\Service\PhotofilesService->insertPhoto() at /srv/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php:272                                                                                                                           
 OCA\Maps\Service\PhotofilesService->addPhoto() at /srv/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php:65                                                                                                                               
 OCA\Maps\Service\PhotofilesService->rescan() at /srv/www/nextcloud/apps/maps/lib/Command/RescanPhotos.php:77                                                                                                                                      
 OCA\Maps\Command\RescanPhotos->rescanUserPhotos() at /srv/www/nextcloud/apps/maps/lib/Command/RescanPhotos.php:68                                                                                                                                 
 OCA\Maps\Command\RescanPhotos->execute() at /srv/www/nextcloud/3rdparty/symfony/console/Command/Command.php:255                                                                                                                                   
 Symfony\Component\Console\Command\Command->run() at /srv/www/nextcloud/3rdparty/symfony/console/Application.php:908                                                                                                                               
 Symfony\Component\Console\Application->doRunCommand() at /srv/www/nextcloud/3rdparty/symfony/console/Application.php:269                                                                                                                          
 Symfony\Component\Console\Application->doRun() at /srv/www/nextcloud/3rdparty/symfony/console/Application.php:145                                                                                                                                 
 Symfony\Component\Console\Application->run() at /srv/www/nextcloud/lib/private/Console/Application.php:213                                                                                                                                        
 OC\Console\Application->run() at /srv/www/nextcloud/console.php:97                                                                                                                                                                                
 require_once() at /srv/www/nextcloud/occ:11                                                                                                                                                                                                       
                                        
In PDOStatement.php line 119:                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                   
  [Doctrine\DBAL\Driver\PDOException (22007)]                                                                                                                                                                                                      
  SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect double value: 'NAN' for column `owncloud`.`oc_maps_photos`.                                                                                                                             
  `lat` at row 1                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                   
Exception trace:                                                                                                                                                                                                                                   
 () at /srv/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:119                                                                                                                                                     
 Doctrine\DBAL\Driver\PDOStatement->execute() at /srv/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:153                                                                                                                     
 Doctrine\DBAL\Statement->execute() at /srv/www/nextcloud/lib/public/AppFramework/Db/Mapper.php:256                                                                                                                                                
 OCP\AppFramework\Db\Mapper->execute() at /srv/www/nextcloud/lib/public/AppFramework/Db/Mapper.php:130                                                                                                                                             
 OCP\AppFramework\Db\Mapper->insert() at /srv/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php:298                                                                                                                                        
 OCA\Maps\Service\PhotofilesService->insertPhoto() at /srv/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php:272                                                                                                                           
 OCA\Maps\Service\PhotofilesService->addPhoto() at /srv/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php:65                                                                                                                               
 OCA\Maps\Service\PhotofilesService->rescan() at /srv/www/nextcloud/apps/maps/lib/Command/RescanPhotos.php:77                                                                                                                                      
 OCA\Maps\Command\RescanPhotos->rescanUserPhotos() at /srv/www/nextcloud/apps/maps/lib/Command/RescanPhotos.php:68                                                                                                                                 
 OCA\Maps\Command\RescanPhotos->execute() at /srv/www/nextcloud/3rdparty/symfony/console/Command/Command.php:255                                                                                                                                   
 Symfony\Component\Console\Command\Command->run() at /srv/www/nextcloud/3rdparty/symfony/console/Application.php:908                                                                                                                               
 Symfony\Component\Console\Application->doRunCommand() at /srv/www/nextcloud/3rdparty/symfony/console/Application.php:269                                                                                                                          
 Symfony\Component\Console\Application->doRun() at /srv/www/nextcloud/3rdparty/symfony/console/Application.php:145                                                                                                                                 
 Symfony\Component\Console\Application->run() at /srv/www/nextcloud/lib/private/Console/Application.php:213                                                                                                                                        
 OC\Console\Application->run() at /srv/www/nextcloud/console.php:97
 require_once() at /srv/www/nextcloud/occ:11

In PDOStatement.php line 117:
                                                                                                                        
  [PDOException (22007)]                                                                                                
  SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect double value: 'NAN' for column `owncloud`.`oc_maps_photos`.  
  `lat` at row 1                                                                                                        
                                                                                                                        

Exception trace:
 () at /srv/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
 PDOStatement->execute() at /srv/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
 Doctrine\DBAL\Driver\PDOStatement->execute() at /srv/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:153                                                                                                                    
 Doctrine\DBAL\Statement->execute() at /srv/www/nextcloud/lib/public/AppFramework/Db/Mapper.php:256
 OCP\AppFramework\Db\Mapper->execute() at /srv/www/nextcloud/lib/public/AppFramework/Db/Mapper.php:130
 OCP\AppFramework\Db\Mapper->insert() at /srv/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php:298
 OCA\Maps\Service\PhotofilesService->insertPhoto() at /srv/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php:272
 OCA\Maps\Service\PhotofilesService->addPhoto() at /srv/www/nextcloud/apps/maps/lib/Service/PhotofilesService.php:65
 OCA\Maps\Service\PhotofilesService->rescan() at /srv/www/nextcloud/apps/maps/lib/Command/RescanPhotos.php:77
 OCA\Maps\Command\RescanPhotos->rescanUserPhotos() at /srv/www/nextcloud/apps/maps/lib/Command/RescanPhotos.php:68
 OCA\Maps\Command\RescanPhotos->execute() at /srv/www/nextcloud/3rdparty/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /srv/www/nextcloud/3rdparty/symfony/console/Application.php:908
 Symfony\Component\Console\Application->doRunCommand() at /srv/www/nextcloud/3rdparty/symfony/console/Application.php:269
 Symfony\Component\Console\Application->doRun() at /srv/www/nextcloud/3rdparty/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /srv/www/nextcloud/lib/private/Console/Application.php:213
 OC\Console\Application->run() at /srv/www/nextcloud/console.php:97
 require_once() at /srv/www/nextcloud/occ:11

maps:scan-photos [<user_id>]

```

### PR DESCRIPTION
**Pull request by eneiluj**
Trying to fix #95.

I don't know how we can get strange lat/lng values but I hope at least the symptom is fixed with this PR.

### CODE REVIEW

**Comment by tacruc** [comment]
> I don't know how we can get strange lat/lng values but I hope at least the symptom is fixed with this PR.

Me neither thats why I just posted the log.

**Comment by eneiluj** [comment]
There's no rush but:

Once #94 is resolved and this fix is tested, accepted and merged, I'll probably publish v0.1.2

**Comment by tacruc** [comment]
Yeah I know, I tested it on my development system with sqlite database but there the problem did not occur even without the fix.
Now I'm testing on my productive system, but there are around 100k pictures on it, so it will take some time.

**Comment by eneiluj** [comment]
Do you mean it occurred without the fix and then you tried again and it didn't occur (still without the fix)?

If so, it will be hard to be sure we avoid this kind of crash.

**Comment by tacruc** [comment]
Do you mean it occurred without the fix and then you tried again and it didn't occur (still without the fix)?

If so, it will be hard to be sure we avoid this kind of crash.

> Do you mean it occurred without the fix and then you tried again and it didn't occur (still without the fix)?
> 
> If so, it will be hard to be sure we avoid this kind of crash.

Yeah, well I putted the picture onto my dev installation, which uses sqlite so there is a difference now I try if I can reporduce the problem on my production system. But this takes time due to the number of pictures.

**Comment by eneiluj** [comment]
You could add the file in a fresh user account and scan for this user only.

**Comment by tacruc** [comment]
Ok the error can be reproduced with mysql database but not with sqlite.

**Comment by eneiluj** [comment]
Were you running this PR's branch while testing on your mysql setup?

**Comment by tacruc** [comment]
No I first tried to reproduce the error. It allways happs on mysql but not on sqlite.
Now I applied the PR, but the error is not fixed.
Can it be that NAN is numeric?

**Comment by eneiluj** [comment]
It seems impossible to me :smile:. I just tried in interactive mode with php7.2 and it's not.

**Comment by eneiluj** [comment]
Ouch, strange thing:

```
if (is_numeric(NAN)) echo 'yep';
```

It appears NAN is numeric and "NAN" is not. But how does the constant NAN reaches the variables we use?

Could you quickly try to change the check and also verify that lat and lng are different than NAN?

**Comment by eneiluj** [comment]
Nice! I guess you tried it and it works :smile:.

**Pull request merged**
