### PR TITLE
Added different mapbox profiles

### PR DESCRIPTION
**Pull request by tacruc**
Added routing with bike and by foot for mapbox.

### CODE REVIEW

**Comment by eneiluj** [comment]
Did you try this in real conditions with an actual Mapbox API key?

**Comment by tacruc** [comment]
Yes, is it not working for you?

**Comment by eneiluj** [comment]
I don't have a Mapbox API key :smile:.

I was just wondering if you added this after having red the doc and if you had the ability to try it for real.

**Comment by tacruc** [comment]
Well I just registered and got an api key. Is a thing of 5 minutes. Than I read the docs.

**Comment by eneiluj** [comment]
After deploying an OSRM server and a GraphHopper one, I became lazy enough not to try Mapbox even if it's quick :smile:.

**Comment by tacruc** [comment]
I didn't get osrm working, as I would need the mapping data for Europe, where it says that it needs arround 150GB of ram. Thats why I went for Graphhopper and mapbox.

**Pull request merged**
