### PR TITLE
Added Regex to detect coordinates in the search query.

### PR DESCRIPTION
**Pull request by tacruc**
Unfortunattly I do net get the results merged with the results from Nominatim.

Signed-off-by: Arne Hamann <kontakt+github@arne.email>

### CODE REVIEW

**Comment by tacruc** [comment]
@eneiluj could you have a look?
I managed to get it working if the length of results is 1.
If the length of results is longer then one I followed the program until line 1789 in script.js but I the it finishes without showing something.

**Comment by eneiluj** [comment]
@tacruc Yep, could you provide 2 examples, one with a single result and one with multiple?

**Comment by tacruc** [comment]
geo:0.0,0.0 single result
0.0,0.0  two results

**Comment by eneiluj** [comment]
Ok, got it, the autocomplete list does not show up because no label/value matches the search string in the result list.

I added the search string in the "fake" coordinate result label and in the nominatim results when we know it's a coordinate search. "0.0,0.0" now displays both the "Point" and "Soul Buoy".

**Comment by eneiluj** [comment]
@tacruc I added a last thing: when choosing a "coordinate" result from multiple ones, no result popup was displayed.

If it's ok for you we can merge that and make the release.

**Comment by tacruc** [comment]
You have to review, I cant :D

**Review by eneiluj — APPROVED** [review]

**Pull request merged**
