### PR TITLE
[Draft] Migrate Admin Settings to Vue

### PR DESCRIPTION
**Pull request by gary-kim**
Still in progress
This may take me several days because I'm very busy at the moment. Sorry about that.

### CODE REVIEW

**Comment by tacruc** [comment]
@gary-kim  this is not ready to merge or review, or?

**Comment by gary-kim** [comment]
Sorry, not done yet. I'll get back to this

**Comment by tacruc** [comment]
@eneiluj  Is this inclueded in the vue Rewrite branch? 
So can this PR be closed?

**Comment by gary-kim** [comment]
I really don't seem to be able to get myself to work on this so let me just close it anyways.

**Pull request closed without merging**
