### PR TITLE
Add proper featurepolicy

### PR DESCRIPTION
**Pull request by rullzer**
Please test with 16, 17 etc.

### CODE REVIEW

**Comment by jancborchardt** [comment]
@AlfredSK could you review this, it fixes the issue you reported at https://github.com/nextcloud/maps/issues/204 :)

**Comment by AlfredSK** [comment]
Ok. I'll check it this evening.

**Comment by rullzer** [comment]
@AlfredSK ah maybe I messed something up there. Fel free to fix the indentation

**Comment by medivh-jay** [comment]
Hello， I have the same problem
my nextcloud version is 17.0.1
and my maps version is the lastest,  0.1.2

**Comment by jancborchardt** [comment]
@paulschwoerer @tacruc @eneiluj could you review? :)

Also @medivh-jay, if you experience the same issue, can you check if this pull request resolves the issue for you?

**Comment by medivh-jay** [comment]
> @paulschwoerer @tacruc @eneiluj could you review? :)
> 
> Also @medivh-jay, if you experience the same issue, can you check if this pull request resolves the issue for you?

Great, this pull request is normal, it works, but why isn't there a merge?

**Comment by medivh-jay** [comment]
> > @paulschwoerer  @tacruc  @eneiluj你能评论吗？:)
> > 还有@ medivh-jay，如果遇到相同的问题，是否可以检查此拉取请求是否为您解决了该问题？
> 
> 太好了，这个拉取请求很正常，可以正常工作，但是为什么不合并呢？

But the location seems to be inaccurate. Is it the problem of the tripartite js plug-in?

**Comment by paulschwoerer** [comment]
LGTM

**Comment by SuperSandro2000** [comment]
This PR did not resolve my problem.

**Pull request merged**
