### PR TITLE
Fixed update photo by file job

### PR DESCRIPTION
**Pull request by tacruc**
Including allready PR #241

### CODE REVIEW

**Comment by tacruc** [comment]
If you change Photos in your could, the next cron job throws the errors discirbed in #247.
They should be gone with this PR.

**Comment by Happyfeet01** [comment]
I have manually changed the files. It works, Cronjob and Maps. Also the Map loads faster.

**Comment by e-alfred** [comment]
Can confirm, after applying the changes of this PR Cron works again.

**Comment by jancborchardt** [comment]
Thanks for testing @Happyfeet01 @e-alfred! :) Would you like to be added to the Nextcloud Maps team here on Github?

**Comment by Happyfeet01** [comment]
> Thanks for testing @Happyfeet01 @e-alfred! :) Would you like to be added to the Nextcloud Maps team here on Github?

Would be really nice, but I must learning coding.. :-)

**Comment by jancborchardt** [comment]
@Happyfeet01 reviewing pull requests is just as important. :)

**Comment by Happyfeet01** [comment]
Sure I do it :-)

**Comment by e-alfred** [comment]
You can add me as well to this repository.

**Comment by e-alfred** [comment]
This is a serious bug, so it would be good to have a new official release now on the app store so the fix is pushed to all installations out there.

**Comment by tacruc** [comment]
Its planed, see #254

**Comment by storrgie** [comment]
It looks like if we wait for #254 it could be a while. This needs a release quickly as it's broken everyone's installs who uses this app. This is a "Featured" app now, breaking the entire instances background processing should be an immediate an urgent fix.

**Comment by e-alfred** [comment]
Well, if #217 is left out (optional anyways) then only a minor fix (#281) and a cosmetic issue (#253) remains which could be merged rather easily.

**Comment by lftsy** [comment]
Thank you for the fix, I confirm it is now. Best Regards. You can close this ticket or there is something else to do ?

**Pull request merged**
