### PR TITLE
refs #85 fix bug with unnamed contacts

### PR DESCRIPTION
**Pull request by eneiluj**
I guess this should do it.

### CODE REVIEW

**Comment by tacruc** [comment]
Maybe not ??? but an empty string?

**Comment by eneiluj** [comment]
Well I don't want to face other problems like generating an avatar image for an empty string etc...

**Comment by tacruc** [comment]
Ok

**Comment by tacruc** [comment]
I found why there is no FN attribute, the cards just have the N attribute.

**Comment by eneiluj** [comment]
Wait, shouldn't we read 'N' when 'FN' is not set? What does the 'N' field contain?

**Comment by eneiluj** [comment]
What do you think about something like
```
'FN'=>$c['FN'] ?? $c['N'] ?? '???',
```
?

**Comment by tacruc** [comment]
```
private function N2FN(string N) {
  return explode(N,';')[3]+explode(N,';')[1]+explode(N,';')[0]
}

'FN'=>$c['FN'] ?? $this->N2FN($c['N']) ?? '???',
```

**Comment by eneiluj** [comment]
I can't understand what you wrote unless you explain what's inside 'N' field.

**Comment by tacruc** [comment]
`Doe;John;;Dr;`

**Comment by eneiluj** [comment]
Ok and do you know when/why 'N' is set and 'FN' is not?

**Comment by tacruc** [comment]
Its an address book I created by importing an CSV file with kaddressbook. It might be an error in the import process.

**Comment by jancborchardt** [comment]
Maybe @skjnldsv from @nextcloud/contacts can help with that Contacts-related question? :)

**Comment by eneiluj** [comment]
Well then `N2FN` could be more secure by verifying the explode gives at least 4 elements. It could be called once and put in a variable too.

Do we agree on something like:

```
private function N2FN(string $n) {
  if ($n) {
    $spl = explode($n,';');
    if (count($spl) >= 4) {
      return $spl[3] + $spl[1] + $spl[0];
    }
    else {
      return null;
    }
  }
  else {
    return null;
  }
}

'FN'=>$c['FN'] ?? $this->N2FN($c['N']) ?? '???',
```
?

**Comment by tacruc** [comment]
Looks good, we probably need to add some spaces between the parts.

**Comment by eneiluj** [comment]
Could you give it a little try?

**Comment by jancborchardt** [comment]
Briefly tested and seems good, but I can’t judge the code.

**Pull request merged**
