### PR TITLE
Support OpenStreetMap vector tiles with Maplibre-gl-js

### PR DESCRIPTION
**Pull request by benstonezhang**
Allow to self-host vector tiles server based on openmaptiles, martin, nginx with cache and maplibre-gl-js.

### CODE REVIEW

**Comment by tacruc** [comment]
Hi @benstonezhang 
Thanks for your contribution 🎉, could you provide me some url to test your PR?
If you don't want to do it publicly you can send me an email or reach me via matrix.

Or send some docs on how to instal the service to test the pr.

**Comment by benstonezhang** [comment]
Sorry, I deploy this on my NAS in home and my ISP provide only private ipv4 address(100.64.0.0/16), so can not access from public internet. I can send you some screenshot if need. I may need to buy a SSD to host data of the postgresql database -- the mechanical hard disk is too slow for postgis select operation. :-(

**Comment by tacruc** [comment]
Can you post some documentation which services are required to deploy this?

**Comment by benstonezhang** [comment]
Service deploy:
1. follow openmaptiles README to [Prepare the Database](https://github.com/openmaptiles/openmaptiles#prepare-the-database)
2. follow openmaptiles README to [Prepare the Layers](https://github.com/openmaptiles/openmaptiles#work-on-layers). I don't want to generate any mbtiles file here, so only run `make import-sql build-style`
3. run `make download-fonts`, then copy the fonts to your selected folder under nginx document root
5. create an instance of martin server [docker](https://github.com/maplibre/martin#using-with-docker), you may want to customize your martin config file by follow martin README [Configuration File](https://github.com/maplibre/martin#configuration-file)
6. update nginx config for [tiles url](https://github.com/maplibre/martin#rewriting-urls)
7. setup [nginx cache](https://github.com/maplibre/martin#caching-tiles)
8. copy generated style.json, sprite.json, sprite.png sprite@2x.json and sprite@2x.png to selected folder under nginx document root
9. update style.json "sources.openmaptiles.url" to nginx martin url, like "https://your_server/martin/tiles/getmvt"
10. update style.json "glyphs" to "https://your_server/your_fonts_dir/{fontstack}/{range}.pbf"
11. update style.json "sprite" to "https://your_server/your_sprite_dir/sprite"

Done

**Review by tacruc — COMMENTED** [review]
Hi @benstonezhang,
sorry for the late reply. I only found time today to setup a tileserver. (Which is still not fully running. But after a while I found a demo url to test your PR:
https://demotiles.maplibre.org/style.json

Blame is on me, but it would have saved some time in the review.

So there is two things which I think need to be done:
- [ ] Rebase the branch onto the current master
- [x] Adapt the CSP as otherwise the tiles won't load
Therefore edit the PageController.php in line 124 add 'maplibreStreetStyleURL'

**Comment by benstonezhang** [comment]
Hi @tacruc, thanks for your review and comments. I'm in a tour and will work to update the PR several days later.

**Comment by benstonezhang** [comment]
Hi @tacruc, PR updated. Please check. Thanks.

**Review by tacruc — APPROVED** [review]
Nice

**Pull request merged**
