### PR TITLE
Temporary fix for navigation style

### PR DESCRIPTION
**Pull request by eneiluj**
This is bringing the "classic" colors back.

### CODE REVIEW

**Comment by tacruc** [comment]
For me it is still not working for the contact categories.

**Comment by eneiluj** [comment]
@tacruc Thanks for the tests. Should be fine now.

**Comment by tacruc** [comment]
Your removed the blue color completly or?
Fine with me.

**Review by tacruc — APPROVED** [review]

**Comment by eneiluj** [comment]
Well I did the simplest fix i could because i didn't want to struggle. It now looks like in NC 19. We'll probably use the default "active" color with Vue navigation components so it will use the theme color.

**Pull request merged**
