### PR TITLE
Catch non numeric warning from pel

### PR DESCRIPTION
**Pull request by tacruc**
This PR silences the warning discussed in #245 
It is fine to just skip the picture as no sample picture had valid geo information. This way the log is not spammed.

 
Signed-off-by: Arne Hamann <kontakt+github@arne.email>

### CODE REVIEW

**Comment by wronny** [comment]
I was not able to reproduce this issue with photos without geo data. I have no experience whether or not to filter out errors from external libraries. To catch the errors from PEL and to log enriched with the photo path might also be an approach from my point of view.

**Comment by tacruc** [comment]
I guess the problem is that there are people who have this error multiple jundred times in there log. Maybe we can catch the error an log something on the warning or debug or info level. 
I have to ask, but I have sample pictures which produces the error.

**Comment by tacruc** [comment]
@ggeorgg would you mind if I share the sample picture with @wronny.

**Comment by ggeorgg** [comment]
No problem. You can share the pictures. I already chose pictures which are not too personal.

**Comment by tacruc** [comment]
@wronny could you write me an email? Then I could share samplepictures with you.

**Comment by wronny** [comment]
@tacruc did you receive my email? Alternatively you can find it in my commits.

**Comment by ggeorgg** [comment]
Do you mean this pull request? https://github.com/pel/pel/pull/154

**Comment by wronny** [comment]
using the provided photos I was able to reproduce the issue of getting 106 lines in nextcloud.log for one photo:
_"A non-numeric value encountered at /var/www/nextcloudtst/apps/maps/vendor/lsolesen/pel/src/PelIfd.php#447"_
However those lines do still occur after applying this change. Again 106 lines.

FYI - How I tested:
I tested using the provided photo LBE_01_20151014_IMG_2796.JPG. Before every new test I removed this photo (incl. "delete permanently" via "deleted files"). 

After adding this logging inside the catch part:
`$this->logger->debug('received error: ' . $exception . ' from PEL for photo: ' . $path );`
I receive the following line in the log:
_{"reqId":"hlMv38hseQIZ4s9TekHp","level":0,"time":"2020-05-06T21:50:02+00:00","remoteAddr":"","user":"--","app":"maps","method":"","url":"--","message":"received error: lsolesen\\pel\\PelDataWindowOffsetException: Offset 262144 not within [0, 7229] in /var/www/nextcloudtst/apps/maps/vendor/lsolesen/pel/src/PelDataWindow.php:243\nStack trace:\n#0 /var/www/nextcloudtst/apps/maps/vendor/lsolesen/pel/src/PelDataWindow.php(368): lsolesen\\pel\\PelDataWindow->validateOffset(262144)\n#1 /var/www/nextcloudtst/apps/maps/vendor/lsolesen/pel/src/PelCanonMakerNotes.php(248): lsolesen\\pel\\PelDataWindow->getShort(262144)\n#2 /var/www/nextcloudtst/apps/maps/vendor/lsolesen/pel/src/PelCanonMakerNotes.php(201): lsolesen\\pel\\PelCanonMakerNotes->parseShotInfo(Object(lsolesen\\pel\\PelIfd), Object(lsolesen\\pel\\PelDataWindow), 262144, 262144)\n#3 /var/www/nextcloudtst/apps/maps/vendor/lsolesen/pel/src/PelIfd.php(406): lsolesen\\pel\\PelCanonMakerNotes->load()\n#4 /var/www/nextcloudtst/apps/maps/vendor/lsolesen/pel/src/PelTiff.php(159): lsolesen\\pel\\PelIfd->load(Object(lsolesen\\pel\\PelDataWindow), 10)\n#5 /var/www/nextcloudtst/apps/maps/vendor/lsolesen/pel/src/PelExif.php(108): lsolesen\\pel\\PelTiff->load(Object(lsolesen\\pel\\PelDataWindow))\n#6 /var/www/nextcloudtst/apps/maps/vendor/lsolesen/pel/src/PelJpeg.php(216): lsolesen\\pel\\PelExif->load(Object(lsolesen\\pel\\PelDataWindow))\n#7 /var/www/nextcloudtst/apps/maps/vendor/lsolesen/pel/src/PelJpeg.php(126): lsolesen\\pel\\PelJpeg->load(Object(lsolesen\\pel\\PelDataWindow))\n#8 /var/www/nextcloudtst/apps/maps/lib/Service/PhotofilesService.php(437): lsolesen\\pel\\PelJpeg->__construct(Object(lsolesen\\pel\\PelDataWindow))\n#9 /var/www/nextcloudtst/apps/maps/lib/Service/PhotofilesService.php(378): OCA\\Maps\\Service\\PhotofilesService->getExifPelBackup(Object(OC\\Files\\Node\\File))\n#10 /var/www/nextcloudtst/apps/maps/lib/Service/PhotofilesService.php(264): OCA\\Maps\\Service\\PhotofilesService->getExif(Object(OC\\Files\\Node\\File))\n#11 /var/www/nextcloudtst/apps/maps/lib/BackgroundJob/AddPhotoJob.php(56): OCA\\Maps\\Service\\PhotofilesService->addPhotoNow(Object(OC\\Files\\Node\\File), 'mtest')\n#12 /var/www/nextcloudtst/lib/public/BackgroundJob/Job.php(79): OCA\\Maps\\BackgroundJob\\AddPhotoJob->run(Array)\n#13 /var/www/nextcloudtst/lib/public/BackgroundJob/QueuedJob.php(48): OCP\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#14 /var/www/nextcloudtst/cron.php(125): OCP\\BackgroundJob\\QueuedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#15 {main} from PEL for photo: /var/nextcloud_data_tst/mtest/files/Photos/test_issue_369/LBE_01_20151014_IMG_2796.JPG","userAgent":"--","version":"18.0.4.2"}_

**Comment by tacruc** [comment]
@wronny Ok the new version is working for me. Cloud you check if it works on your system?

**Pull request merged**
